version: '3'

services:
  worker:
    container_name: crypto
    hostname: crypto
    restart: always
    image: crypto
    volumes:
      - /data/apps/auto_crypto/logs:/var/log
      - /data/apps/auto_crypto/crypto.env:/opt/apps/crypto.env

volumes:
  logs:
    driver: local
